name: sematext_logger
description: A Flutter package that provides Sematext logging implementation.
version: 0.0.1

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: ">=3.13.9"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: