name: dixo_logger
description: A Flutter package that provides an interface of Logger and a Console logger implementation.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
